/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_SETTINGS_PB_H_INCLUDED
#define PB_SETTINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _InputMode {
    InputMode_XInput = 0,
    InputMode_Switch = 1,
    InputMode_Hid = 2,
    InputMode_Config = 255
} InputMode;

typedef enum _DpadMode {
    DpadMode_Digital = 0,
    DpadMode_LeftAnalog = 1,
    DpadMode_RightAnalog = 2
} DpadMode;

/* Struct definitions */
typedef struct _GamepadOptions {
    bool has_inputMode;
    InputMode inputMode;
    bool has_dpadMode;
    DpadMode dpadMode;
    /* optional bool invertXAxis = 3; */
    bool has_invertYAxis;
    bool invertYAxis;
} GamepadOptions;

typedef struct _BuzzerAddon {
    bool has_enabled;
    bool enabled;
    bool has_pin;
    int32_t pin;
    bool has_volume;
    uint32_t volume;
} BuzzerAddon;

typedef struct _Settings {
    bool has_gamepadOptions;
    GamepadOptions gamepadOptions;
    /* optional BoardOptions boardOptions = 2; */
    bool has_buzzerAddon;
    BuzzerAddon buzzerAddon;
} Settings;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _InputMode_MIN InputMode_XInput
#define _InputMode_MAX InputMode_Config
#define _InputMode_ARRAYSIZE ((InputMode)(InputMode_Config+1))

#define _DpadMode_MIN DpadMode_Digital
#define _DpadMode_MAX DpadMode_RightAnalog
#define _DpadMode_ARRAYSIZE ((DpadMode)(DpadMode_RightAnalog+1))


#define GamepadOptions_inputMode_ENUMTYPE InputMode
#define GamepadOptions_dpadMode_ENUMTYPE DpadMode



/* Initializer values for message structs */
#define Settings_init_default                    {false, GamepadOptions_init_default, false, BuzzerAddon_init_default}
#define GamepadOptions_init_default              {false, _InputMode_MIN, false, _DpadMode_MIN, false, 0}
#define BuzzerAddon_init_default                 {false, 0, false, -1, false, 100u}
#define Settings_init_zero                       {false, GamepadOptions_init_zero, false, BuzzerAddon_init_zero}
#define GamepadOptions_init_zero                 {false, _InputMode_MIN, false, _DpadMode_MIN, false, 0}
#define BuzzerAddon_init_zero                    {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GamepadOptions_inputMode_tag             1
#define GamepadOptions_dpadMode_tag              2
#define GamepadOptions_invertYAxis_tag           4
#define BuzzerAddon_enabled_tag                  1
#define BuzzerAddon_pin_tag                      2
#define BuzzerAddon_volume_tag                   3
#define Settings_gamepadOptions_tag              1
#define Settings_buzzerAddon_tag                 3

/* Struct field encoding specification for nanopb */
#define Settings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gamepadOptions,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  buzzerAddon,       3)
#define Settings_CALLBACK NULL
#define Settings_DEFAULT NULL
#define Settings_gamepadOptions_MSGTYPE GamepadOptions
#define Settings_buzzerAddon_MSGTYPE BuzzerAddon

#define GamepadOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    inputMode,         1) \
X(a, STATIC,   OPTIONAL, UENUM,    dpadMode,          2) \
X(a, STATIC,   OPTIONAL, BOOL,     invertYAxis,       4)
#define GamepadOptions_CALLBACK NULL
#define GamepadOptions_DEFAULT NULL

#define BuzzerAddon_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           1) \
X(a, STATIC,   OPTIONAL, INT32,    pin,               2) \
X(a, STATIC,   OPTIONAL, UINT32,   volume,            3)
#define BuzzerAddon_CALLBACK NULL
#define BuzzerAddon_DEFAULT (const pb_byte_t*)"\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x18\x64\x00"

extern const pb_msgdesc_t Settings_msg;
extern const pb_msgdesc_t GamepadOptions_msg;
extern const pb_msgdesc_t BuzzerAddon_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Settings_fields &Settings_msg
#define GamepadOptions_fields &GamepadOptions_msg
#define BuzzerAddon_fields &BuzzerAddon_msg

/* Maximum encoded size of messages (where known) */
#define BuzzerAddon_size                         19
#define GamepadOptions_size                      7
#define Settings_size                            30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
