/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "settings.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Settings, Settings, AUTO)


PB_BIND(GamepadOptions, GamepadOptions, AUTO)


PB_BIND(BoardOptions, BoardOptions, AUTO)





