/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "complete.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Settings, Settings, 2)


PB_BIND(GamepadOptions, GamepadOptions, AUTO)


PB_BIND(ButtonLayoutParams, ButtonLayoutParams, AUTO)


PB_BIND(ButtonLayoutCustomOptions, ButtonLayoutCustomOptions, AUTO)


PB_BIND(BoardOptions, BoardOptions, 2)


PB_BIND(AddonOptions, AddonOptions, 2)


PB_BIND(SplashImage, SplashImage, 2)


PB_BIND(LEDOptions, LEDOptions, AUTO)











