name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.5.2

      - name: Checkout pico-sdk/1.5.0
        uses: actions/checkout@v3
        with:
          repository: raspberrypi/pico-sdk
          ref: 1.5.0
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/pico-sdk
        run: git submodule update --init

      - name: Get core count
        id: core_count
        run: cat /proc/cpuinfo  | grep processor | wc -l

      - name: Configure CMake
        run: PICO_SDK_PATH=../pico-sdk cmake ${{github.workspace}}/v0-base -B ${{github.workspace}}/v0-base/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/v0-base/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}
