name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.5.2

      - name: Checkout pico-sdk/1.5.0
        uses: actions/checkout@v3
        with:
          repository: raspberrypi/pico-sdk
          ref: 1.5.0
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/pico-sdk
        run: git submodule update --init

      - name: Get core count
        id: core_count
        run: cat /proc/cpuinfo  | grep processor | wc -l

      - name: v0-base - Configure CMake
        run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk cmake ${{github.workspace}}/v0-base -B ${{github.workspace}}/v0-base/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: v0-base - Build
        run: cmake --build ${{github.workspace}}/v0-base/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}

      - name: v0-base - Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: v0-base
          path: ${{github.workspace}}/v0-base/build/v0-base.uf2
          if-no-files-found: error

      - name: v1-added_fields - Configure CMake
        run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk cmake ${{github.workspace}}/v1-added_fields -B ${{github.workspace}}/v1-added_fields/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: v1-added_fields - Build
        run: cmake --build ${{github.workspace}}/v1-added_fields/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}

      - name: v1-added_fields - Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: v1-added_fields
          path: ${{github.workspace}}/v1-added_fields/build/v1-added_fields.uf2
          if-no-files-found: error

      - name: v2-removed_fields - Configure CMake
        run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk cmake ${{github.workspace}}/v2-removed_fields -B ${{github.workspace}}/v2-removed_fields/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: v2-removed_fields - Build
        run: cmake --build ${{github.workspace}}/v2-removed_fields/build --config ${{env.BUILD_TYPE}} --parallel ${{steps.core_count.outputs.output}}

      - name: v2-removed_fields - Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: v2-removed_fields
          path: ${{github.workspace}}/v2-removed_fields/build/v2-removed_fields.uf2
          if-no-files-found: error
